### PR TITLE
Adding GitHub Actions.

### PR DESCRIPTION
**Pull request by oleg-andreyev**
As promised https://twitter.com/suckup_de/status/1355413828088061957?s=20

---
This change is [Reviewable](https://reviewable.io/reviews/voku/arrayy/43)

### CODE REVIEW

**Comment by oleg-andreyev** [comment]
Probably you need to configure GH Actions in repository settings.
Here are the results
https://github.com/oleg-andreyev/Arrayy/pull/1/checks

**Comment by oleg-andreyev** [comment]
@voku as soon as you'll preview PR, we'll squash everything.

**Comment by voku** [comment]
Thanks for the migration from Travis CI to GitHub Actions. :+1: 

I will try to use this as template for some of my other open source repos.

**Comment by oleg-andreyev** [comment]
Glad to help :) feel free to reach out if you need any other help

**Pull request merged**
